FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=27
ENV MYSQL_DATABASE=spring-mysql
ENV MYSQL_USER=Omar
ENV MYSQL_PASSWORD=Noomy

# Just for me, Not needed if I map the port in the command with -p X:X
EXPOSE 3306