
package com.sumerge.course_recommender.course.recommenders;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CourseService", targetNamespace = "com.sumerge.course-wsdl", wsdlLocation = "http://localhost:8088/courseSOAPServiceMock?wsdl")
public class CourseService
    extends Service
{

    private static final URL COURSESERVICE_WSDL_LOCATION;
    private static final WebServiceException COURSESERVICE_EXCEPTION;
    private static final QName COURSESERVICE_QNAME = new QName("com.sumerge.course-wsdl", "CourseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/courseSOAPServiceMock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSESERVICE_WSDL_LOCATION = url;
        COURSESERVICE_EXCEPTION = e;
    }

    public CourseService() {
        super(__getWsdlLocation(), COURSESERVICE_QNAME);
    }

    public CourseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSESERVICE_QNAME, features);
    }

    public CourseService(URL wsdlLocation) {
        super(wsdlLocation, COURSESERVICE_QNAME);
    }

    public CourseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSESERVICE_QNAME, features);
    }

    public CourseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoursePortType
     */
    @WebEndpoint(name = "CoursePort")
    public CoursePortType getCoursePort() {
        return super.getPort(new QName("com.sumerge.course-wsdl", "CoursePort"), CoursePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoursePortType
     */
    @WebEndpoint(name = "CoursePort")
    public CoursePortType getCoursePort(WebServiceFeature... features) {
        return super.getPort(new QName("com.sumerge.course-wsdl", "CoursePort"), CoursePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSESERVICE_EXCEPTION!= null) {
            throw COURSESERVICE_EXCEPTION;
        }
        return COURSESERVICE_WSDL_LOCATION;
    }

}
