
package com.sumerge.course_recommender.course.recommenders;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CoursePortType", targetNamespace = "com.sumerge.course-wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoursePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sumerge.course_recommender.course.recommenders.GetCoursesResponse
     */
    @WebMethod(action = "com/sumerge/course-wsdl/getCourses")
    @WebResult(name = "GetCoursesResponse", targetNamespace = "com.sumerge.course-wsdl", partName = "parameters")
    public GetCoursesResponse getCourses(
        @WebParam(name = "GetCoursesRequest", targetNamespace = "com.sumerge.course-wsdl", partName = "parameters")
        String parameters);

}
